function [ newState, stateSvdCovNew, stateNoise, observNoise, internal ] = sckf( state, svdCovState, stateNoise, observNoise, observation, model, ctrl1, ctrl2 )
    % sckf. Square Root form of Cubature Kalman Filter (Sigma-Point Kalman Filter variant).
    %
    %   [ newState, stateSvdCovNew, stateNoise, observNoise, internal ] = sckf( state, svdCovState, stateNoise, observNoise, observation, model, ctrl1, ctrl2 )
    %
    %   This filter assumes the following standard state-space model:
    %
    %     x(k) = f[x(k-1), v(k-1), u1(k-1)];
    %     z(k) = h[x(k), n(k), u2(k)],
    %
    %   where
    %       x  - is the system state;
    %       v  - the process noise;
    %       n  - the observation noise;
    %       u1 - the exogenous input to the state;
    %       f  - transition function;
    %       u2 - the exogenous input to the state observation function;
    %       z  - the noisy observation of the system.
    %
    %   INPUT
    %         state         state mean at time k-1 ( xh(k-1) );
    %         svdCovState   square root factor of matrix through Singular Value Decomposition of state covariance at time k-1;
    %         stateNoise    process noise data structure (must be of type 'gaussian' or 'combo-gaussian');
    %         observNoise   observation noise data structure (must be of type 'gaussian' or 'combo-gaussian');
    %         observation   noisy observations starting at time k ( z(k) );
    %         model         inference data structure, which fully describes filtration issue (generated by inferenceDataGenerator function);
    %         ctrl1         exogenous input to state transition function at time k-1 ( u1(k-1) );
    %         ctrl2         exogenous input to state observation function at time k ( u2(k) );
    %
    %   OUTPUT
    %         newState                  estimates of state at time k ( E[x(t)|z(1), z(2), ..., z(t)] for t = k );
    %         svdCovState               estimate of square root factor of matrix through Singular Value Decomposition of state covariance at time k;
    %         stateNoise                process noise data structure (possibly updated);
    %         observNoise               observation noise data structure (possibly updated);
    %         internal                  <<optional>> internal variables data structure;
    %           .meanPredictedState         	predicted state mean ( E[x(t) | z(1), z(2), ..., z(t-1)] for t = k );
    %           .sqrtCovState                   predicted of Cholesky factor of state covariance matrix at time k;
    %           .predictedObservMean            predicted observation ( E[z(k)|Z(k-1)] );
    %           .inov                           inovation signal;
    %           .sqrtObservCov                  predicted of Cholesky factor of observation covariance;
    %           .filterGain                     filter gain.
    %
    %% error checking
    if (nargin ~= 8 && nargin ~= 6)
        error('[ sckf ] Not enough input arguments (should be 6 or 8).');
    end
    
    if (model.stateDimension ~= size(state, 1))
        error('[ sckf ] Prior state dimension differs from model.stateDimension');
    end
    
    if (model.stateDimension ~= size(svdCovState, 1))
        error('[ sckf ] Prior state covariance dimension differs from model.stateDimension');
    end
    
    if (model.observationDimension ~= size(observation, 1));
        error('[ sckf ] Observation dimension differs from model.observationDimension');
    end
    
    %%
    stateDim = model.stateDimension;
    
    if (model.controlInputDimension == 0)
        ctrl1 = [];
    end
    
    if (model.control2InputDimension == 0)
        ctrl2 = [];
    end
    
    %% calculate cubature points
    numCubPointSet = 2*stateDim;
    cubatureSet  = cvecrep(state, numCubPointSet) + svdCovState*(sqrt(numCubPointSet/2)*[eye(stateDim) -eye(stateDim)]);
    
    %% propagate cubature-points through process model
    predictState = model.stateTransitionFun(model, cubatureSet, cvecrep(stateNoise.mean, numCubPointSet), ctrl1);
    predictStateMean = sum(predictState, 2) / numCubPointSet;
    weightedCenteredSet = (predictState - cvecrep(predictStateMean, numCubPointSet)) / sqrt(numCubPointSet);
    [~, sqrtPredictedCov] = qr([ weightedCenteredSet stateNoise.covariance]', 0);
    sqrtPredictedCov = sqrtPredictedCov';
    
    %% calculate cubature points for measurement
    cubatureSet2 = cvecrep(predictStateMean, numCubPointSet) + sqrtPredictedCov*(sqrt(numCubPointSet/2)*[eye(stateDim) -eye(stateDim)]);
    
    %% propagate through observation model
    predictObs = model.stateObservationFun(model, cubatureSet2, cvecrep(observNoise.mean, numCubPointSet), ctrl2);
    predictObsMean = sum(predictObs, 2) / numCubPointSet;
    
    %% measurement update (correction)
    x = (cubatureSet2-cvecrep(predictStateMean, numCubPointSet)) / sqrt(numCubPointSet);
    z = (predictObs-cvecrep(predictObsMean, numCubPointSet)) / sqrt(numCubPointSet);
    
    [~, sqrtObsCov] = qr([z observNoise.covariance]', 0);
    sqrtObsCov = sqrtObsCov';
    
    crossCov = x*z';
    
    filterGain = (crossCov / sqrtObsCov') / sqrtObsCov;
    
    if isempty(model.innovationModelFunc)
        inov = observation - predictObsMean;
    else
        inov = model.innovationModelFunc( model, observation, predictObsMean);
    end
    
    newState = predictStateMean + filterGain * inov;
    
    [~, stateSvdCovNew] = qr([(x - filterGain*z)  filterGain*observNoise.covariance]', 0);
    stateSvdCovNew = stateSvdCovNew';
    
    %% build additional ouptut param (required for debug)
    if nargout > 4
        internal.meanPredictedState    = predictStateMean;
        internal.predictedStateCov     = sqrtPredictedCov*sqrtPredictedCov';
        internal.predictedObservMean   = predictObsMean;
        internal.inov                  = inov;
        internal.predictedObservCov    = sqrtObsCov*sqrtObsCov';
        internal.filterGain            = filterGain;
    end
end