%задаём систему ДУ для вычисления координат на момент времени Ti
function dy = EquationOfMotion(time, state, acceleration, angularVelocity, tEpoch, sampleTime)

EarthRadius = 6378.136; %[km] - Earth's equatorial radius
MuE = 398600.4418; %[км^3/с^2] - Earth gravity const
J2 = .00108262575;
J3 = -.000002533;
J4 = -0.000001616;

iterationNumber = fix(time / sampleTime);

if (isvector(acceleration))
    accelerationCurrent = acceleration;
else
    accelerationCurrent = acceleration(iterationNumber, :);
end

if (isvector(angularVelocity)) 
    angularVelocityCurrent = angularVelocity;
else
    angularVelocityCurrent = angularVelocity(iterationNumber, :);
end

r = sqrt( state(1)^2 + state(2)^2 + state(3)^2 ); % distance from Earth center to Satellity center
po = EarthRadius / r;

dy = zeros(10,1);

sunInfluence = SunInfluence(tEpoch, state(1:3));
moonInfluence = MoonInfluence(tEpoch, state(1:3));

quaternion = state(7:10)';
rotatedAccelearation = quatrotate(quaternion, accelerationCurrent);

dy(1:3) = state(4:6);
dy(4) = -(MuE*state(1)/r^3)*(...
        1 ...
        + J2*3/2*po^2*(1-5*(state(3)/r)^2) ...
        + J3*po^3*5/2*(3-7*(state(3)/r)^2)*state(3)/r ...
        - J4*po^4*5/8*(3-42*(state(3)/r)^2+63*(state(3)/r)^4) ...
    ) ...
    + rotatedAccelearation(1) ...
    + sunInfluence(1) ...
    + moonInfluence(1);
dy(5) = -(MuE*state(2)/r^3)*(...
        1 ...
        + J2*3/2*po^2*(1-5*(state(3)/r)^2) ...
        + J3*po^3*5/2*(3-7*(state(3)/r)^2)*state(3)/r ...
        - J4*po^4*5/8*(3-42*(state(3)/r)^2+63*(state(3)/r)^4) ...
    ) ...
    + rotatedAccelearation(2) ...
    + sunInfluence(2) ...
    + moonInfluence(2);
dy(6) = -(MuE*state(3)/r^3)*(...
        1 ... 
        + J2*3/2*po^2*(3-5*(state(3)/r)^2) ...
        + J3*po^3*5/2*(3-7*po^2)*state(3)/r ...
        - J4*po^4*5/8*(3-42*(state(3)/r)^2+63*(state(3)/r)^4)...
    ) ... 
    + rotatedAccelearation(3) ...
    + sunInfluence(3) ...
    + moonInfluence(3);
dy(7:10) = .5 * quatmultiply(quaternion, [0, angularVelocityCurrent]);